import type {
  ContactForm,
  ContactPerson,
  CustomerContact,
} from "@/lib/modules/crm";

import { validatePhoneNumber } from "./customer";

const CONTACT_MAX_LENGTHS = {
  firstName: 100,
  lastName: 100,
  position: 100,
  role: 100,
  department: 100,
  email: 150,
  phone: 30,
  alternatePhone: 30,
} as const;

const PREFERRED_CHANNELS = ["email", "phone", "whatsapp"] as const;

function validateEmail(email: string): boolean {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim());
}

function validateLength(
  value: string | null | undefined,
  max: number,
): boolean {
  return !value || value.trim().length <= max;
}

function isValidPreferredChannel(value: string): boolean {
  return PREFERRED_CHANNELS.includes(
    value as (typeof PREFERRED_CHANNELS)[number],
  );
}

/**
 * Validate one contact.
 *
 * Error keys are generated by the caller because the same
 * validation is used for primary and additional contacts.
 */
function validateContactFields(
  contact: {
    firstName?: string;
    lastName?: string;
    email?: string;
    phone?: string;
    alternatePhone?: string;
    department?: string;
    position?: string;
    role?: string;
    preferred_channel?: string;
  },
  setError: (field: string, message: string) => void,
) {
  const firstName = contact.firstName?.trim() ?? "";
  const lastName = contact.lastName?.trim() ?? "";
  const email = contact.email?.trim() ?? "";
  const phone = contact.phone?.trim() ?? "";
  const alternatePhone = contact.alternatePhone?.trim() ?? "";
  const department = contact.department?.trim() ?? "";
  const position = contact.position?.trim() ?? "";
  const role = contact.role?.trim() ?? "";
  const preferredChannel = contact.preferred_channel?.trim() ?? "";

  // ------------------------------------------------------------
  // First name
  // ------------------------------------------------------------

  if (!firstName) {
    setError("firstName", "First name is required.");
  } else if (firstName.length > CONTACT_MAX_LENGTHS.firstName) {
    setError(
      "firstName",
      `First name cannot exceed ${CONTACT_MAX_LENGTHS.firstName} characters.`,
    );
  }

  // ------------------------------------------------------------
  // Last name
  // ------------------------------------------------------------

  if (!lastName) {
    setError("lastName", "Last name is required.");
  } else if (lastName.length > CONTACT_MAX_LENGTHS.lastName) {
    setError(
      "lastName",
      `Last name cannot exceed ${CONTACT_MAX_LENGTHS.lastName} characters.`,
    );
  }

  // ------------------------------------------------------------
  // Email
  // ------------------------------------------------------------

  if (!email) {
    setError("email", "Email is required.");
  } else if (email.length > CONTACT_MAX_LENGTHS.email) {
    setError(
      "email",
      `Email cannot exceed ${CONTACT_MAX_LENGTHS.email} characters.`,
    );
  } else if (!validateEmail(email)) {
    setError("email", "Enter a valid email address.");
  }

  // ------------------------------------------------------------
  // Phone
  // ------------------------------------------------------------

  if (!phone) {
    setError("phone", "Phone number is required.");
  } else if (phone.length > CONTACT_MAX_LENGTHS.phone) {
    setError(
      "phone",
      `Phone number cannot exceed ${CONTACT_MAX_LENGTHS.phone} characters.`,
    );
  } else if (!validatePhoneNumber(phone)) {
    setError("phone", "Enter a valid phone number with 10-15 digits.");
  }

  // ------------------------------------------------------------
  // Alternate phone
  // ------------------------------------------------------------
  console.log(alternatePhone, "alternatePhone");
  if (alternatePhone) {
    if (alternatePhone.length > CONTACT_MAX_LENGTHS.alternatePhone) {
      setError(
        "alternatePhone",
        `Alternate phone cannot exceed ${CONTACT_MAX_LENGTHS.alternatePhone} characters.`,
      );
    } else if (!validatePhoneNumber(alternatePhone)) {
      setError(
        "alternatePhone",
        "Enter a valid alternate phone number with 10-15 digits.",
      );
    } else if (alternatePhone === phone) {
      setError(
        "alternatePhone",
        "Alternate phone cannot be the same as phone number.",
      );
    }
  }

  // ------------------------------------------------------------
  // Department
  // ------------------------------------------------------------

  if (!department) {
    setError("department", "Department is required.");
  } else if (department.length > CONTACT_MAX_LENGTHS.department) {
    setError(
      "department",
      `Department cannot exceed ${CONTACT_MAX_LENGTHS.department} characters.`,
    );
  }

  // ------------------------------------------------------------
  // Position
  // ------------------------------------------------------------

  if (position.length > CONTACT_MAX_LENGTHS.position) {
    setError(
      "position",
      `Position cannot exceed ${CONTACT_MAX_LENGTHS.position} characters.`,
    );
  }

  // ------------------------------------------------------------
  // Role
  // ------------------------------------------------------------

  if (!role) {
    setError("role", "Role is required.");
  } else if (role.length > CONTACT_MAX_LENGTHS.role) {
    setError(
      "role",
      `Role cannot exceed ${CONTACT_MAX_LENGTHS.role} characters.`,
    );
  }

  // ------------------------------------------------------------
  // Preferred channel
  // ------------------------------------------------------------

  if (!preferredChannel) {
    setError("preferred_channel", "Preferred channel is required.");
  } else if (!isValidPreferredChannel(preferredChannel)) {
    setError("preferred_channel", "Select a valid preferred channel.");
  }
}

export function validateContacts(customerId: string, contacts: ContactForm[]) {
  const errors: Record<string, string> = {};

  if (!customerId?.trim()) {
    errors.customerId = "Customer is required.";
  }

  contacts.forEach((contact, index) => {
    validateContactFields(
      {
        firstName: contact.firstName,
        lastName: contact.lastName,
        email: contact.email,
        phone: contact.phone,
        alternatePhone: contact.alternatePhone,
        department: contact.department,
        position: contact.position,
        role: contact.role,
        preferred_channel: contact.preferred_channel,
      },
      (field, message) => {
        errors[`${field}-${index}`] = message;
      },
    );
  });

  return {
    valid: Object.keys(errors).length === 0,
    errors,
  };
}

export function validateContacts2(
  primary: CustomerContact,
  additional: ContactPerson[],
) {
  const errors: Record<string, string> = {};

  // ------------------------------------------------------------
  // Primary contact
  // ------------------------------------------------------------

  validateContactFields(
    {
      firstName: primary.first_name,
      lastName: primary.last_name,
      email: primary.email,
      phone: primary.phone,
      alternatePhone: primary.alternate_phone,
      department: primary.department,
      position: primary.position,
      role: primary.role,
      preferred_channel: primary.preferred_channel,
    },
    (field, message) => {
      const primaryKeyMap: Record<string, string> = {
        firstName: "primaryFirstName",
        lastName: "primaryLastName",
        email: "primaryEmail",
        phone: "primaryPhone",
        alternatePhone: "primaryAlternatePhone",
        department: "primaryDepartment",
        position: "primaryPosition",
        role: "primaryRole",
        preferred_channel: "primaryPreferredChannel",
      };

      errors[primaryKeyMap[field] ?? field] = message;
    },
  );

  // ------------------------------------------------------------
  // Additional contacts
  // ------------------------------------------------------------

  additional.forEach((contact, index) => {
    validateContactFields(
      {
        firstName: contact.first_name,
        lastName: contact.last_name,
        email: contact.email,
        phone: contact.phone,
        alternatePhone: contact.alternate_phone,
        department: contact.department,
        position: contact.position,
        role: contact.role,
        preferred_channel: contact.preferred_channel,
      },
      (field, message) => {
        errors[`additional_${index}_${field}`] = message;
      },
    );
  });

  return {
    valid: Object.keys(errors).length === 0,
    errors,
  };
}

export function buildContactsPayload(contacts: ContactForm[]) {
  return {
    additional_contacts: contacts.map((contact) => ({
      first_name: contact.firstName,
      last_name: contact.lastName,
      email: contact.email,
      phone: contact.phone,
      alternate_phone: contact.alternatePhone,
      department: contact.department,
      position: contact.role,
      role: contact.role,
      preferred_channel: contact.preferred_channel,
    })),
  };
}

export function buildUpdateContactsPayload(form: CustomerContact) {
  return {
    primary_contact: {
      first_name: form.first_name,
      last_name: form.last_name,
      email: form.email,
      phone: form.phone,
      alternate_phone: form.alternate_phone,
      department: form.department,
      position: form.position,
      role: form.role,
      preferred_channel: form.preferred_channel,
    },

    additional_contacts: form.additional_contacts.map((contact) => ({
      id: contact.id,
      first_name: contact.first_name,
      last_name: contact.last_name,
      email: contact.email,
      phone: contact.phone,
      alternate_phone: contact.alternate_phone,
      department: contact.department,
      position: contact.role,
      role: contact.role,
      preferred_channel: contact.preferred_channel,
    })),
  };
}
