from enum import Enum
class ProductErrorCode(str, Enum):
    PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"

    PRODUCT_NAME_ALREADY_EXISTS = "PRODUCT_NAME_ALREADY_EXISTS"
    PRODUCT_CODE_ALREADY_EXISTS = "PRODUCT_CODE_ALREADY_EXISTS"

    PRODUCT_ALREADY_ACTIVE = "PRODUCT_ALREADY_ACTIVE"
    PRODUCT_ALREADY_INACTIVE = "PRODUCT_ALREADY_INACTIVE"

    INVALID_PRODUCT_TYPE = "INVALID_PRODUCT_TYPE"