from __future__ import annotations
from enum import Enum


class PaymentErrorCode(str, Enum):
    PAYMENT_NOT_FOUND = "PAYMENT_NOT_FOUND"

    PAYMENT_EXCEEDS_BALANCE = "PAYMENT_EXCEEDS_BALANCE"
    PAYMENT_AMOUNT_INVALID = "PAYMENT_AMOUNT_INVALID"

    PAYMENT_REFERENCE_EXISTS = "PAYMENT_REFERENCE_EXISTS"

    INVOICE_NOT_FOUND = "INVOICE_NOT_FOUND"
    INVOICE_ALREADY_PAID = "INVOICE_ALREADY_PAID"
    INVOICE_VOID = "INVOICE_VOID"