from __future__ import annotations
from enum import Enum

class OrderErrorCode(str, Enum):
    ORDER_NOT_FOUND          = "ORDER_NOT_FOUND"
    ORDER_CANNOT_BE_CANCELLED = "ORDER_CANNOT_BE_CANCELLED"
    ORDER_CANNOT_BE_CONFIRMED = "ORDER_CANNOT_BE_CONFIRMED"
    ORDER_CANNOT_BE_SUBMITTED = "ORDER_CANNOT_BE_SUBMITTED"
    ORDER_CANNOT_BE_CLOSED   = "ORDER_CANNOT_BE_CLOSED"
    ORDER_NOT_EDITABLE       = "ORDER_NOT_EDITABLE"
    ORDER_ITEMS_REQUIRED     = "ORDER_ITEMS_REQUIRED"