from __future__ import annotations
from enum import Enum

class OrderErrorCode(str, Enum):
    ORDER_NOT_FOUND          = "ORDER_NOT_FOUND"
    ORDER_CANNOT_BE_CANCELLED = "ORDER_CANNOT_BE_CANCELLED"
    ORDER_CANNOT_BE_SUBMITTED = "ORDER_CANNOT_BE_SUBMITTED"
    ORDER_NOT_EDITABLE       = "ORDER_NOT_EDITABLE"
    ORDER_ITEMS_REQUIRED     = "ORDER_ITEMS_REQUIRED"
    ORDER_ALREADY_ASSIGNED_TO_TRIP     = "ORDER_ALREADY_ASSIGNED_TO_TRIP"
    ORDER_CANNOT_CONFIRM_DELIVERY     = "ORDER_CANNOT_CONFIRM_DELIVERY"
    ORDER_CANNOT_ASSIGN_TRIP     = "ORDER_CANNOT_ASSIGN_TRIP"
    ORDER_CANNOT_GENERATE_INVOICE     = "ORDER_CANNOT_GENERATE_INVOICE"
    ORDER_ALREADY_HAS_INVOICE     = "ORDER_ALREADY_HAS_INVOICE"
    ORDER_CANNOT_BE_CONFIRMED = "ORDER_CANNOT_BE_CONFIRMED"
    INVALID_FULFILLMENT_TRANSITION = "INVALID_FULFILLMENT_TRANSITION"