from __future__ import annotations
from enum import Enum

class FleetErrorCode(str, Enum):
    DRIVER_NOT_FOUND          = "DRIVER_NOT_FOUND"
    VEHICLE_NOT_FOUND         = "VEHICLE_NOT_FOUND"
    TRIP_NOT_FOUND            = "TRIP_NOT_FOUND"
    DRIVER_NOT_AVAILABLE      = "DRIVER_NOT_AVAILABLE"
    VEHICLE_NOT_AVAILABLE     = "VEHICLE_NOT_AVAILABLE"
    TRIP_CANNOT_BE_ASSIGNED   = "TRIP_CANNOT_BE_ASSIGNED"
    TRIP_CANNOT_BE_DISPATCHED = "TRIP_CANNOT_BE_DISPATCHED"
    TRIP_CANNOT_BE_STARTED    = "TRIP_CANNOT_BE_STARTED"
    TRIP_CANNOT_BE_COMPLETED  = "TRIP_CANNOT_BE_COMPLETED"
    TRIP_CANNOT_BE_CANCELLED  = "TRIP_CANNOT_BE_CANCELLED"
    ORDER_CANNOT_BE_LINKED    = "ORDER_CANNOT_BE_LINKED"
    LICENSE_NUMBER_IN_USE     = "LICENSE_NUMBER_IN_USE"
    PLATE_NUMBER_IN_USE       = "PLATE_NUMBER_IN_USE"