# from __future__ import annotations
# from enum import Enum

# class InventoryErrorCode(str, Enum):
#     INVENTORY_ITEM_NOT_FOUND     = "INVENTORY_ITEM_NOT_FOUND"
#     INVENTORY_ITEM_NOT_AVAILABLE = "INVENTORY_ITEM_NOT_AVAILABLE"
#     INSUFFICIENT_STOCK           = "INSUFFICIENT_STOCK"
#     LOCATION_NOT_FOUND           = "LOCATION_NOT_FOUND"
#     PRODUCT_NOT_TRACKED          = "PRODUCT_NOT_TRACKED"
#     PRODUCT_NOT_CONSUMABLE       = "PRODUCT_NOT_CONSUMABLE"
#     CANNOT_RETURN_ITEM           = "CANNOT_RETURN_ITEM"


from __future__ import annotations

from enum import Enum


class InventoryErrorCode(str, Enum):
    INVENTORY_ITEM_NOT_FOUND = "INVENTORY_ITEM_NOT_FOUND"
    INVENTORY_ITEM_NOT_AVAILABLE = "INVENTORY_ITEM_NOT_AVAILABLE"
    ITEM_ALREADY_RESERVED = "ITEM_ALREADY_RESERVED"

    INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK"

    LOCATION_NOT_FOUND = "LOCATION_NOT_FOUND"

    PRODUCT_NOT_TRACKED = "PRODUCT_NOT_TRACKED"
    PRODUCT_NOT_CONSUMABLE = "PRODUCT_NOT_CONSUMABLE"

    CANNOT_RETURN_ITEM = "CANNOT_RETURN_ITEM"