"""add_vendors_and_procurement_items

Revision ID: 2144ff5b9113
Revises: e0ea3b6f6818
Create Date: 2026-05-15 10:58:29.212212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2144ff5b9113'
down_revision: Union[str, None] = 'e0ea3b6f6818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('equipment', 'ppe', 'technical', 'consumables', 'food_beverage', 'services', 'it', 'logistics', name='vendorcategory'), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('account_number', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='vendorstatus'), nullable=False),
    sa.Column('added_by', mysql.CHAR(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procurement_items',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('request_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.Enum('pieces', 'litres', 'kg', 'boxes', 'metres', 'hours', 'sets', 'cartons', 'units', name='itemunit'), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['procurement_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('procurement_requests', sa.Column('category', sa.Enum('consumables', 'technical', 'services', 'capital', name='procurementcategory'), nullable=False))
    op.add_column('procurement_requests', sa.Column('priority', sa.Enum('routine', 'urgent', 'emergency', name='procurementpriority'), nullable=False))
    op.add_column('procurement_requests', sa.Column('justification', sa.Text(), nullable=True))
    op.add_column('procurement_requests', sa.Column('vendor_id', mysql.CHAR(length=36), nullable=True))
    op.add_column('procurement_requests', sa.Column('attachment_url', sa.String(length=500), nullable=True))
    op.add_column('procurement_requests', sa.Column('attachment_name', sa.String(length=255), nullable=True))
    op.add_column('procurement_requests', sa.Column('po_url', sa.String(length=500), nullable=True))
    op.alter_column('procurement_requests', 'required_by',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
    op.create_foreign_key(None, 'procurement_requests', 'vendors', ['vendor_id'], ['id'])
    op.drop_column('procurement_requests', 'vendor_contact')
    op.drop_column('procurement_requests', 'description')
    op.drop_column('procurement_requests', 'department')
    op.drop_column('procurement_requests', 'estimated_amount')
    op.drop_column('procurement_requests', 'vendor_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procurement_requests', sa.Column('vendor_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('procurement_requests', sa.Column('estimated_amount', mysql.DECIMAL(precision=15, scale=2), nullable=True))
    op.add_column('procurement_requests', sa.Column('department', mysql.ENUM('operations', 'finance', 'safety', 'hr', 'it', 'logistics', 'executive', 'engineering'), nullable=False))
    op.add_column('procurement_requests', sa.Column('description', mysql.TEXT(), nullable=True))
    op.add_column('procurement_requests', sa.Column('vendor_contact', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'procurement_requests', type_='foreignkey')
    op.alter_column('procurement_requests', 'required_by',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.drop_column('procurement_requests', 'po_url')
    op.drop_column('procurement_requests', 'attachment_name')
    op.drop_column('procurement_requests', 'attachment_url')
    op.drop_column('procurement_requests', 'vendor_id')
    op.drop_column('procurement_requests', 'justification')
    op.drop_column('procurement_requests', 'priority')
    op.drop_column('procurement_requests', 'category')
    op.drop_table('procurement_items')
    op.drop_table('vendors')
    # ### end Alembic commands ###
