"""add_customers_table

Revision ID: 7aa20a48e6a6
Revises: d4e5f6a7b8c9
Create Date: 2026-06-24 17:08:31.404285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7aa20a48e6a6'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
<<<<<<< HEAD
    # ### commands auto generated by Alembic - please adjust! ###
=======
>>>>>>> c7b4c06 (merging)
    op.create_table('customers',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('customer_no', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('individual', 'corporate', 'government', name='customertype'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', name='customerstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_customer_no'), 'customers', ['customer_no'], unique=True)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_customers_status'), 'customers', ['status'], unique=False)
<<<<<<< HEAD
    op.drop_index(op.f('ix_safety_checklist_items_template_id'), table_name='safety_checklist_items')
    op.drop_index(op.f('uq_safety_checklist_items_template_key'), table_name='safety_checklist_items')
    op.drop_table('safety_checklist_items')
    op.drop_index(op.f('ix_safety_checklist_templates_code'), table_name='safety_checklist_templates')
    op.drop_index(op.f('ix_safety_checklist_templates_is_active'), table_name='safety_checklist_templates')
    op.drop_index(op.f('ix_safety_checklist_templates_parent_type'), table_name='safety_checklist_templates')
    op.drop_index(op.f('ix_safety_checklist_templates_stage'), table_name='safety_checklist_templates')
    op.drop_index(op.f('ix_safety_checklist_templates_version'), table_name='safety_checklist_templates')
    op.drop_index(op.f('uq_safety_checklist_templates_code_version'), table_name='safety_checklist_templates')
    op.drop_table('safety_checklist_templates')
    op.drop_index(op.f('ix_safety_checklist_responses_item_id'), table_name='safety_checklist_responses')
    op.drop_index(op.f('ix_safety_checklist_responses_parent'), table_name='safety_checklist_responses')
    op.drop_index(op.f('ix_safety_checklist_responses_parent_id'), table_name='safety_checklist_responses')
    op.drop_index(op.f('ix_safety_checklist_responses_parent_type'), table_name='safety_checklist_responses')
    op.drop_index(op.f('ix_safety_checklist_responses_response_group_id'), table_name='safety_checklist_responses')
    op.drop_index(op.f('ix_safety_checklist_responses_template_id'), table_name='safety_checklist_responses')
    op.drop_table('safety_checklist_responses')
    op.drop_index(op.f('line_manager_id'), table_name='employees')
    op.drop_index(op.f('uq_vendors_vendor_code'), table_name='vendors')
    op.create_index(op.f('ix_vendors_vendor_code'), 'vendors', ['vendor_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendors_vendor_code'), table_name='vendors')
    op.create_index(op.f('uq_vendors_vendor_code'), 'vendors', ['vendor_code'], unique=True)
    op.create_index(op.f('line_manager_id'), 'employees', ['operating_manager_id'], unique=False)
    op.create_table('safety_checklist_responses',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('template_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('template_code_snapshot', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('template_name_snapshot', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('template_version', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stage_snapshot', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('item_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('item_key_snapshot', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('label_snapshot', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('input_type_snapshot', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('options_json_snapshot', mysql.JSON(), nullable=True),
    sa.Column('is_required_snapshot', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('sort_order_snapshot', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_type', mysql.ENUM('work_authorization', 'work_closeout', 'closeout_review', 'incident_hse_review', 'work_initiation', 'incident_report'), nullable=False),
    sa.Column('parent_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('response_group_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('value_boolean', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('value_text', mysql.TEXT(), nullable=True),
    sa.Column('value_number', mysql.DECIMAL(precision=18, scale=4), nullable=True),
    sa.Column('value_date', sa.DATE(), nullable=True),
    sa.Column('value_datetime', mysql.DATETIME(), nullable=True),
    sa.Column('selected_option', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('comment', mysql.TEXT(), nullable=True),
    sa.Column('answered_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('answered_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['answered_by'], ['users.id'], name=op.f('safety_checklist_responses_ibfk_1')),
    sa.ForeignKeyConstraint(['item_id'], ['safety_checklist_items.id'], name=op.f('safety_checklist_responses_ibfk_2')),
    sa.ForeignKeyConstraint(['template_id'], ['safety_checklist_templates.id'], name=op.f('safety_checklist_responses_ibfk_3')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_checklist_responses_template_id'), 'safety_checklist_responses', ['template_id'], unique=False)
    op.create_index(op.f('ix_safety_checklist_responses_response_group_id'), 'safety_checklist_responses', ['response_group_id'], unique=False)
    op.create_index(op.f('ix_safety_checklist_responses_parent_type'), 'safety_checklist_responses', ['parent_type'], unique=False)
    op.create_index(op.f('ix_safety_checklist_responses_parent_id'), 'safety_checklist_responses', ['parent_id'], unique=False)
    op.create_index(op.f('ix_safety_checklist_responses_parent'), 'safety_checklist_responses', ['parent_type', 'parent_id'], unique=False)
    op.create_index(op.f('ix_safety_checklist_responses_item_id'), 'safety_checklist_responses', ['item_id'], unique=False)
    op.create_table('safety_checklist_templates',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('parent_type', mysql.ENUM('work_authorization', 'work_closeout', 'closeout_review', 'incident_hse_review', 'work_initiation', 'incident_report'), nullable=False),
    sa.Column('stage', mysql.ENUM('risk_assessment', 'inspection', 'monitoring', 'hse_review', 'completion', 'closeout_review'), nullable=False),
    sa.Column('version', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('uq_safety_checklist_templates_code_version'), 'safety_checklist_templates', ['code', 'version'], unique=True)
    op.create_index(op.f('ix_safety_checklist_templates_version'), 'safety_checklist_templates', ['version'], unique=False)
    op.create_index(op.f('ix_safety_checklist_templates_stage'), 'safety_checklist_templates', ['stage'], unique=False)
    op.create_index(op.f('ix_safety_checklist_templates_parent_type'), 'safety_checklist_templates', ['parent_type'], unique=False)
    op.create_index(op.f('ix_safety_checklist_templates_is_active'), 'safety_checklist_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_safety_checklist_templates_code'), 'safety_checklist_templates', ['code'], unique=False)
    op.create_table('safety_checklist_items',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('template_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('item_key', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('label', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('input_type', mysql.ENUM('boolean', 'text', 'number', 'date', 'datetime', 'enum'), nullable=False),
    sa.Column('options_json', mysql.JSON(), nullable=True),
    sa.Column('default_value', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_required', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('severity_weight', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sort_order', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['safety_checklist_templates.id'], name=op.f('safety_checklist_items_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('uq_safety_checklist_items_template_key'), 'safety_checklist_items', ['template_id', 'item_key'], unique=True)
    op.create_index(op.f('ix_safety_checklist_items_template_id'), 'safety_checklist_items', ['template_id'], unique=False)
=======


def downgrade() -> None:
>>>>>>> c7b4c06 (merging)
    op.drop_index(op.f('ix_customers_status'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_no'), table_name='customers')
    op.drop_table('customers')
<<<<<<< HEAD
    # ### end Alembic commands ###
=======
>>>>>>> c7b4c06 (merging)
