"""initial schema

Revision ID: e0ea3b6f6818
Revises: 
Create Date: 2026-05-14 10:20:30.624488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e0ea3b6f6818'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'admin', 'approver_l1', 'approver_l2', 'approver_l3', 'staff', 'viewer', name='userrole'), nullable=False),
    sa.Column('department', sa.Enum('operations', 'finance', 'safety', 'hr', 'it', 'logistics', 'executive', 'engineering', name='department'), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('approval_requests',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('workflow_type', sa.String(length=100), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=False),
    sa.Column('reference_label', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending', 'in_progress', 'approved', 'rejected', 'returned', name='approvalstatus'), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_reference_id'), 'approval_requests', ['reference_id'], unique=False)
    op.create_table('fleet_vehicles',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.Enum('cng_truck', 'lng_tanker', 'service_van', 'pickup', 'bus', name='vehicletype'), nullable=False),
    sa.Column('status', sa.Enum('available', 'in_use', 'maintenance', 'retired', name='vehiclestatus'), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('driver_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fleet_vehicles_plate_number'), 'fleet_vehicles', ['plate_number'], unique=True)
    op.create_table('otp_codes',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('purpose', sa.Enum('email_verification', 'password_reset', name='otppurpose'), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procurement_requests',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department', sa.Enum('operations', 'finance', 'safety', 'hr', 'it', 'logistics', 'executive', 'engineering', name='department'), nullable=False),
    sa.Column('estimated_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending', 'in_progress', 'approved', 'rejected', 'completed', 'cancelled', name='procurementstatus'), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('vendor_contact', sa.String(length=255), nullable=True),
    sa.Column('required_by', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurement_requests_reference'), 'procurement_requests', ['reference'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('approval_history',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('request_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['approval_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_steps',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('request_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.Enum('individual', 'group', name='steptype'), nullable=False),
    sa.Column('group_rule', sa.Enum('any_one', 'all_must', name='grouprule'), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending', 'in_progress', 'approved', 'rejected', 'returned', name='approvalstatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['approval_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_requests',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('vehicle_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'completed', 'cancelled', name='maintenancestatus'), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['fleet_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_requests_reference'), 'maintenance_requests', ['reference'], unique=True)
    op.create_table('step_assignees',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('step_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('decision', sa.Enum('pending', 'approved', 'rejected', 'returned', name='decisionstatus'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['step_id'], ['approval_steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('customers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('step_assignees')
    op.drop_index(op.f('ix_maintenance_requests_reference'), table_name='maintenance_requests')
    op.drop_table('maintenance_requests')
    op.drop_table('approval_steps')
    op.drop_table('approval_history')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_procurement_requests_reference'), table_name='procurement_requests')
    op.drop_table('procurement_requests')
    op.drop_table('otp_codes')
    op.drop_index(op.f('ix_fleet_vehicles_plate_number'), table_name='fleet_vehicles')
    op.drop_table('fleet_vehicles')
    op.drop_index(op.f('ix_approval_requests_reference_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
