"""cleanup_remove_procurement_fleet_approvals_otp_update_users

Revision ID: eaf95fb8a51a
Revises: 03314566dcfe
Create Date: 2026-06-19 13:18:50.261048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eaf95fb8a51a'
down_revision: Union[str, None] = '03314566dcfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop in child-first order to avoid FK constraint errors.
    # Indexes are dropped automatically by MySQL when the table is dropped.
    op.drop_table('approval_history')    # child of approval_requests
    op.drop_table('step_assignees')      # child of approval_steps
    op.drop_table('approval_steps')      # child of approval_requests
    op.drop_table('approval_requests')
    op.drop_table('otp_codes')
    op.drop_table('procurement_items')   # child of procurement_requests
    op.drop_table('procurement_requests')
    op.drop_table('maintenance_requests')  # child of fleet_vehicles
    op.drop_table('fleet_vehicles')

    # Update users table
    op.add_column('users', sa.Column('profile_picture_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('setup_token', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('setup_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_setup_token'), 'users', ['setup_token'], unique=False)
    op.create_foreign_key('fk_users_profile_picture', 'users', 'documents', ['profile_picture_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'profile_picture')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_setup_token'), table_name='users')
    op.drop_column('users', 'setup_token_expires_at')
    op.drop_column('users', 'setup_token')
    op.drop_column('users', 'profile_picture_id')
    op.create_table('procurement_items',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('request_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('quantity', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('unit', mysql.ENUM('pieces', 'litres', 'kg', 'boxes', 'metres', 'hours', 'sets', 'cartons', 'units'), nullable=False),
    sa.Column('unit_cost', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('total_cost', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['procurement_requests.id'], name=op.f('procurement_items_ibfk_1')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp_codes',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=6), nullable=False),
    sa.Column('purpose', mysql.ENUM('email_verification', 'password_reset'), nullable=False),
    sa.Column('is_used', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('otp_codes_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_requests',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('workflow_type', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('reference_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('reference_label', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('status', mysql.ENUM('draft', 'pending', 'in_progress', 'approved', 'rejected', 'returned'), nullable=False),
    sa.Column('current_step', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_steps', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('approval_requests_ibfk_1')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_reference_id'), 'approval_requests', ['reference_id'], unique=False)
    op.create_table('step_assignees',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('step_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('decision', mysql.ENUM('pending', 'approved', 'rejected', 'returned'), nullable=False),
    sa.Column('decided_at', mysql.DATETIME(), nullable=True),
    sa.Column('comment', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['step_id'], ['approval_steps.id'], name=op.f('step_assignees_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('step_assignees_ibfk_2')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_steps',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('request_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('step_number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('step_type', mysql.ENUM('individual', 'group'), nullable=False),
    sa.Column('group_rule', mysql.ENUM('any_one', 'all_must'), nullable=True),
    sa.Column('status', mysql.ENUM('draft', 'pending', 'in_progress', 'approved', 'rejected', 'returned'), nullable=False),
    sa.Column('completed_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['approval_requests.id'], name=op.f('approval_steps_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procurement_requests',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('reference', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('status', mysql.ENUM('draft', 'submitted', 'ordered', 'delivered', 'cancelled'), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('required_by', sa.DATE(), nullable=True),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('category', mysql.ENUM('consumables', 'technical', 'services', 'capital'), nullable=False),
    sa.Column('priority', mysql.ENUM('routine', 'urgent', 'emergency'), nullable=False),
    sa.Column('justification', mysql.TEXT(), nullable=True),
    sa.Column('vendor_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('attachment_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('attachment_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('po_url', mysql.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('procurement_requests_ibfk_1')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('procurement_requests_ibfk_2')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurement_requests_reference'), 'procurement_requests', ['reference'], unique=True)
    op.create_table('maintenance_requests',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('reference', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('vehicle_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('status', mysql.ENUM('scheduled', 'in_progress', 'completed', 'cancelled'), nullable=False),
    sa.Column('scheduled_date', mysql.DATETIME(), nullable=True),
    sa.Column('completed_date', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('maintenance_requests_ibfk_1')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['fleet_vehicles.id'], name=op.f('maintenance_requests_ibfk_2')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_requests_reference'), 'maintenance_requests', ['reference'], unique=True)
    op.create_table('fleet_vehicles',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('plate_number', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('make', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('model', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vehicle_type', mysql.ENUM('cng_truck', 'lng_tanker', 'service_van', 'pickup', 'bus'), nullable=False),
    sa.Column('status', mysql.ENUM('available', 'in_use', 'maintenance', 'retired'), nullable=False),
    sa.Column('mileage', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('driver_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], name=op.f('fleet_vehicles_ibfk_1')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fleet_vehicles_plate_number'), 'fleet_vehicles', ['plate_number'], unique=True)
    op.create_table('approval_history',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('request_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('action', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('actor_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('step_number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', mysql.TEXT(), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('approval_history_ibfk_1')),
    sa.ForeignKeyConstraint(['request_id'], ['approval_requests.id'], name=op.f('approval_history_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
