from __future__ import annotations

from enum import Enum


class TripErrorCode(str, Enum):
    TRIP_NOT_FOUND = "TRIP_NOT_FOUND"

    TRIP_CANNOT_BE_ASSIGNED = "TRIP_CANNOT_BE_ASSIGNED"
    TRIP_CANNOT_BE_DISPATCHED = "TRIP_CANNOT_BE_DISPATCHED"
    TRIP_CANNOT_BE_STARTED = "TRIP_CANNOT_BE_STARTED"
    TRIP_CANNOT_BE_COMPLETED = "TRIP_CANNOT_BE_COMPLETED"
    TRIP_CANNOT_BE_CANCELLED = "TRIP_CANNOT_BE_CANCELLED"

    ORDER_CANNOT_BE_LINKED = "ORDER_CANNOT_BE_LINKED"

    DRIVER_NOT_ASSIGNED = "DRIVER_NOT_ASSIGNED"
    VEHICLE_NOT_ASSIGNED = "VEHICLE_NOT_ASSIGNED"
    TRIP_CANNOT_BE_MARKED_READY = "TRIP_CANNOT_BE_MARKED_READY"
    TRIP_CANNOT_BE_MODIFIED = "TRIP_CANNOT_BE_MODIFIED"