from enum import Enum


class AuthErrorCode(str, Enum):
    INVALID_CREDENTIALS      = "INVALID_CREDENTIALS"
    TOKEN_EXPIRED            = "TOKEN_EXPIRED"
    INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS"
    ACCOUNT_INACTIVE         = "ACCOUNT_INACTIVE"